// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promobile.Data;

namespace Promobile.Migrations
{
    [DbContext(typeof(PromobileContext))]
    [Migration("20191018195825_insertedParcelValueFieldOnProduct")]
    partial class insertedParcelValueFieldOnProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Promobile.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<string>("ImagePath");

                    b.Property<string>("MobileImagePath");

                    b.Property<string>("Name");

                    b.Property<int>("RegionDivision");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Promobile.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Promobile.Models.PromotionalProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<string>("FeaturedOptionalText");

                    b.Property<decimal>("ForwardedPrice");

                    b.Property<string>("ImagePath");

                    b.Property<decimal>("InCashPrice");

                    b.Property<int>("InputParcelsQuantity");

                    b.Property<decimal>("MonthlyTax");

                    b.Property<string>("Name");

                    b.Property<decimal>("ParcelValue");

                    b.Property<int>("ParcelsQuantity");

                    b.Property<int?>("ProductCategoryId");

                    b.Property<string>("ProductHash");

                    b.Property<string>("QrCodeString");

                    b.Property<int>("RegionDivision");

                    b.Property<int>("Status");

                    b.Property<decimal>("YearlyTax");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("PromotionalProducts");
                });

            modelBuilder.Entity("Promobile.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("RegionDivision");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Promobile.Models.PromotionalProduct", b =>
                {
                    b.HasOne("Promobile.Models.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
